import json
import os
import re
from typing import Any, Dict, List, Optional, Tuple

import fitz  # PyMuPDF
import pdfplumber

from app.services.llm_service import get_llm_service
from app.utils.logger import get_logger

logger = get_logger("pdf_parser_service")

# ── Stage-1: per-page intermediate heading heuristic ─────────────────────────
_PAGE_HEADING_SIZE_RATIO = 1.2

# ── Stage-3: output cap ──────────────────────────────────────────────────────
_MAX_OUTPUT_CHUNKS = 10

# Substrings (case-insensitive) that should be removed from content wherever found.
_NOISE_PHRASES: List[str] = [
    "Generated by Kimi.ai",
]


class PdfParserService:
    """Three-stage PDF-to-KB pipeline: parse → LLM chunk → finalize.

    All public methods are synchronous and CPU/IO-bound.
    Run them via run_in_threadpool when calling from an async context.
    """

    # ── public API ────────────────────────────────────────────────────────────

    def parse(self, file_path: str) -> List[Dict[str, Any]]:
        """
        Stage 1 – extract raw text/table blocks from every page.

        Returns one dict per page:
            {
                "page": int,
                "heading": str,
                "content": str,
                "font_size": float,
                "blocks": [
                    {
                        "type": "text" | "table",
                        "bbox": [x0, y0, x1, y1],
                        "page": int,
                        "lines": [{"text", "font_name", "font_size", "bbox"}],  # text only
                        "rows": [[cell, ...]],                                   # table only
                    }
                ],
            }
        """
        logger.info(f"Starting PDF parse: {file_path}")
        fitz_doc    = fitz.open(file_path)
        plumber_doc = pdfplumber.open(file_path)

        try:
            if len(fitz_doc) == 0:
                logger.warning(f"PDF has zero pages: {os.path.basename(file_path)}")
                return []

            pages = []
            for page_idx in range(len(fitz_doc)):
                page_number  = page_idx + 1
                fitz_page    = fitz_doc[page_idx]
                plumber_page = plumber_doc.pages[page_idx]

                text_blocks   = self._extract_text_blocks(fitz_page, page_number)
                table_blocks  = self._extract_table_blocks(plumber_page, page_number)
                merged_blocks = self._merge_blocks(text_blocks, table_blocks)
                heading, heading_size, content = self._derive_heading_and_content(merged_blocks)

                pages.append({
                    "page":      page_number,
                    "heading":   heading,
                    "content":   content,
                    "font_size": heading_size,
                    "blocks":    merged_blocks,
                })

            total_spans = sum(
                len(b["lines"])
                for page in pages
                for b in page["blocks"]
                if b["type"] == "text"
            )
            if total_spans == 0:
                logger.warning(
                    f"No text extracted from '{os.path.basename(file_path)}' "
                    "— document may be a scanned image"
                )

            logger.info(f"Parsed {len(pages)} pages from '{os.path.basename(file_path)}'")
            return pages

        finally:
            fitz_doc.close()
            plumber_doc.close()

    def chunk(self, pages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Stage 2 – semantic chunking via LLM.

        Returns:
            [{"heading": str, "content": str, "page_numbers": [int, ...], "keywords": [str, ...]}]
        """
        all_pages = sorted(p["page"] for p in pages)
        all_content = _pages_to_document_text(pages)

        if not all_content:
            logger.warning("No document text available for LLM chunking")
            return []

        logger.info(f"LLM chunking {len(pages)} pages ({len(all_content)} chars)")
        chunks = _llm_chunk_document(all_content, all_pages)
        logger.info(f"Chunking produced {len(chunks)} sections")
        return chunks

    def finalize(
        self,
        chunks:            List[Dict[str, Any]],
        pages:             List[Dict[str, Any]],
        source_pdf:        str,
        nfo_name:          str,
        insurer_name:      str,
        insurer_id:        Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """
        Stage 3 – enrich each chunk into the final KB entry shape.

        Args:
            chunks:       output of chunk()
            pages:        output of parse()
            source_pdf:   original filename of the uploaded PDF
            nfo_name:     fund/product name provided by the user
            insurer_name: insurer name provided by the user
            insurer_id:   optional insurer ID provided by the user

        Returns:
            [
                {
                    "term": "<NFO Name> (deck section X/Y)",
                    "content": str,
                    "keywords": [str, ...],
                    "product_type": "nfo",
                    "metadata": {
                        "source_pdf": str,
                        "chunk_index": int,
                        "chunk_total": int,
                        "nfo_name": str,
                        "section_heading": str,
                        "extraction_strategy": "llm",
                        "page_numbers": [int, ...],
                        "insurer_name": str,
                        "insurer_id": int | None,
                        "nfo_date": None,
                    },
                }
            ]
        """
        product_name = nfo_name.strip()

        logger.info(
            f"Finalizing {len(chunks)} chunks — nfo_name='{product_name}'  "
            f"insurer='{insurer_name}' (id={insurer_id})  source='{source_pdf}'"
        )

        # Drop chunks with no meaningful content, or whose only content
        # duplicates the product/nfo name (title-only pages add no KB value).
        def _is_redundant(c: Dict[str, Any]) -> bool:
            content = _strip_noise(c.get("content", "").strip())
            if not content and not c.get("heading", "").strip():
                return True
            # Content is redundant if it collapses to the product name (ignoring
            # case, punctuation, and whitespace).
            normalise = lambda s: re.sub(r"[^a-z0-9]", "", s.lower())
            return bool(content) and normalise(content) == normalise(product_name)

        valid = [c for c in chunks if not _is_redundant(c)]
        dropped = len(chunks) - len(valid)
        if dropped:
            logger.info(f"Dropped {dropped} redundant/empty chunk(s) after validation")

        # Merge down to at most _MAX_OUTPUT_CHUNKS if we have too many.
        if len(valid) > _MAX_OUTPUT_CHUNKS:
            valid = _merge_to_limit(valid, _MAX_OUTPUT_CHUNKS)
            logger.info(f"Merged into {len(valid)} chunks to stay within limit")

        total  = len(valid)
        result = []
        for idx, chunk in enumerate(valid, start=1):
            heading   = chunk.get("heading", "").strip()
            content   = _strip_noise(chunk.get("content", "").strip())
            page_nums = chunk.get("page_numbers", [])

            keywords = chunk.get("keywords") or []

            result.append({
                "term":         f"{product_name} (deck section {idx}/{total})",
                "content":      content,
                "keywords":     keywords,
                "product_type": "nfo",
                "metadata": {
                    "source_pdf":          source_pdf,
                    "chunk_index":         idx,
                    "chunk_total":         total,
                    "nfo_name":            product_name,
                    "section_heading":     heading,
                    "extraction_strategy": "llm",
                    "page_numbers":        page_nums,
                    "insurer_name":        insurer_name,
                    "insurer_id":          insurer_id,
                    "nfo_date":            None,
                },
            })

        return result

    # ── Stage-1 helpers ───────────────────────────────────────────────────────

    def _extract_text_blocks(
        self, page: fitz.Page, page_number: int
    ) -> List[Dict[str, Any]]:
        raw    = page.get_text("dict")
        blocks: List[Dict[str, Any]] = []

        for block in raw.get("blocks", []):
            if block.get("type") != 0:  # skip image blocks
                continue

            lines: List[Dict[str, Any]] = []
            for line in block.get("lines", []):
                for span in line.get("spans", []):
                    text = span.get("text", "").strip()
                    if not text:
                        continue
                    lines.append({
                        "text":      text,
                        "font_name": span.get("font", ""),
                        "font_size": round(span.get("size", 0.0), 2),
                        "bbox":      list(span.get("bbox", [])),
                    })

            if lines:
                blocks.append({
                    "type":  "text",
                    "bbox":  list(block.get("bbox", [])),
                    "page":  page_number,
                    "lines": lines,
                })

        return blocks

    def _extract_table_blocks(
        self, page: "pdfplumber.page.Page", page_number: int
    ) -> List[Dict[str, Any]]:
        blocks: List[Dict[str, Any]] = []

        for table in page.find_tables():
            rows = [
                [cell if cell is not None else "" for cell in row]
                for row in table.extract()
            ]
            blocks.append({
                "type": "table",
                "bbox": list(table.bbox),
                "page": page_number,
                "rows": rows,
            })

        return blocks

    def _merge_blocks(
        self,
        text_blocks:  List[Dict[str, Any]],
        table_blocks: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Drop text blocks that overlap a table bbox, then sort all by y."""
        if not table_blocks:
            return text_blocks

        table_bboxes = [b["bbox"] for b in table_blocks]

        def overlaps_any_table(bbox: list) -> bool:
            x0, y0, x1, y1 = bbox
            for tx0, ty0, tx1, ty1 in table_bboxes:
                if x0 < tx1 and x1 > tx0 and y0 < ty1 and y1 > ty0:
                    return True
            return False

        filtered = [b for b in text_blocks if not overlaps_any_table(b["bbox"])]
        merged   = filtered + table_blocks
        merged.sort(key=lambda b: b["bbox"][1])
        return merged

    def _derive_heading_and_content(
        self, blocks: List[Dict[str, Any]]
    ) -> Tuple[str, float, str]:
        """Per-page summary for the intermediate structure.

        Picks the *first* block whose max font size equals the page maximum
        and exceeds the median-based threshold.  Everything else is content.
        """
        all_sizes = [
            l["font_size"]
            for b in blocks if b["type"] == "text"
            for l in b["lines"]
        ]
        if not all_sizes:
            return "", 0.0, ""

        median_size = _median(all_sizes)
        max_size    = max(all_sizes)
        threshold   = median_size * _PAGE_HEADING_SIZE_RATIO

        heading_text  = ""
        heading_size  = 0.0
        content_parts: List[str] = []
        heading_found = False

        for b in blocks:
            if b["type"] == "table":
                table_text = _table_to_text(b["rows"])
                if table_text:
                    content_parts.append(table_text)
                continue

            block_max = max(l["font_size"] for l in b["lines"])
            if (
                not heading_found
                and abs(block_max - max_size) < 0.1
                and block_max >= threshold
            ):
                heading_text = " ".join(
                    l["text"] for l in b["lines"] if l["font_size"] >= threshold
                ).strip()
                heading_size  = block_max
                heading_found = True
            else:
                text = _block_text(b)
                if text:
                    content_parts.append(text)

        return heading_text, heading_size, "\n\n".join(content_parts).strip()

    # ── Stage-3 helpers ───────────────────────────────────────────────────────

    def _infer_product_name(
        self, pages: List[Dict[str, Any]], source_pdf: str
    ) -> str:
        """Return the product name from the largest-font block on page 1,
        falling back to the PDF filename stem."""
        if pages:
            best_size:  float               = 0.0
            best_lines: List[Dict[str, Any]] = []

            for block in pages[0].get("blocks", []):
                if block["type"] != "text":
                    continue
                block_max = max(l["font_size"] for l in block["lines"])
                if block_max > best_size:
                    best_size  = block_max
                    best_lines = block["lines"]

            if best_lines:
                text = " ".join(
                    l["text"].strip() for l in best_lines if l["text"].strip()
                )
                if text:
                    return _clean_product_name(text)

        stem = os.path.splitext(os.path.basename(source_pdf))[0]
        return _clean_product_name(stem)


# ── module-level utilities ────────────────────────────────────────────────────

def _pages_to_document_text(pages: List[Dict[str, Any]]) -> str:
    """Flatten parsed pages into one document string for LLM chunking."""
    parts: List[str] = []
    for page in pages:
        for block in page.get("blocks", []):
            if block["type"] == "table":
                text = _table_to_text(block["rows"])
            else:
                text = _block_text(block)
            if text:
                parts.append(text)
    return "\n\n".join(parts).strip()


def _merge_to_limit(
    chunks: List[Dict[str, Any]], limit: int
) -> List[Dict[str, Any]]:
    """Merge *chunks* into exactly *limit* groups by distributing evenly.

    Within each group the first non-empty heading is kept; content blocks are
    joined with double newlines; page numbers are unioned and sorted.
    """
    n        = len(chunks)
    merged   = []
    group_sz = n / limit  # float — e.g. 23 chunks → 2.3 per bucket

    for bucket in range(limit):
        start = round(bucket * group_sz)
        end   = round((bucket + 1) * group_sz)
        group = chunks[start:end]
        if not group:
            continue

        heading   = next((c["heading"] for c in group if c.get("heading", "").strip()), "")
        content   = "\n\n".join(c["content"] for c in group if c.get("content", "").strip())
        page_nums = sorted({p for c in group for p in c.get("page_numbers", [])})
        keywords: List[str] = []
        seen_keywords: set[str] = set()
        for c in group:
            for kw in c.get("keywords") or []:
                if kw not in seen_keywords:
                    seen_keywords.add(kw)
                    keywords.append(kw)

        merged.append({
            "heading":      heading,
            "content":      content.strip(),
            "page_numbers": page_nums,
            "keywords":     keywords,
        })

    return merged


_LLM_SPLIT_PROMPT = """\
You are a semantic document chunking agent for a Retrieval-Augmented Generation (RAG) pipeline.

Your task is to identify semantically meaningful chunk boundaries in the document below.

Guidelines:
- Preserve the original document text exactly — do NOT rewrite or summarize it.
- Preserve the original order of the document.
- Split only when a genuinely new topic or concept begins.
- Keep related paragraphs together so each chunk represents one complete idea.
- If a heading introduces an example, analogy, illustration, use case, table, FAQ, or continuation of the previous concept, keep it in the same chunk.
- Never split inside tables, bullet lists, numbered lists, examples, equations, or code blocks.
- If a concept spans multiple pages, keep it as a single chunk.
- Prioritize semantic coherence over equal chunk sizes.
- Aim for roughly 5–10 chunks for a typical NFO deck unless the document is very short.

For each chunk, generate 5–10 high-quality keywords:
- Use meaningful, searchable concepts and domain-specific phrases.
- Include important entities, product names, financial terms, and key topics where applicable.
- Avoid duplicate keywords or different grammatical forms of the same word.
- Avoid generic keywords like "value", "invest", "strategy", or "information" unless they are part of a meaningful phrase.

IMPORTANT: Do NOT return the full chunk text. The system will slice the original document using your boundaries.

Output format:
- Return ONLY a JSON array of objects in document order.
- Each object must have:
  - "heading": the section title if one exists, otherwise an empty string
  - "start_marker": an exact substring copied character-for-character from the input where this chunk begins (use the section heading or the first line of the section)
  - "keywords": an array of 5–10 keyword strings for that chunk
- The first object's start_marker must be the opening text of the document.
- Every start_marker must appear verbatim in the input.
- No explanation, no markdown fences, just the raw JSON array.

Text:
{text}
"""


def _extract_llm_text(response: Any) -> str:
    raw_content = response.content if hasattr(response, "content") else response
    if isinstance(raw_content, list):
        return "".join(
            block.get("text", "") if isinstance(block, dict) else str(block)
            for block in raw_content
        ).strip()
    return str(raw_content).strip()


def _extract_json_array(raw: str) -> List[Any]:
    cleaned = re.sub(r"^```(?:json)?\s*", "", raw.strip())
    cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        parsed = json.loads(cleaned)
        if isinstance(parsed, list):
            return parsed
    except json.JSONDecodeError:
        pass

    start = cleaned.find("[")
    end = cleaned.rfind("]")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No JSON array found in LLM response")

    parsed = json.loads(cleaned[start : end + 1])
    if not isinstance(parsed, list):
        raise ValueError("LLM response is not a JSON array")
    return parsed


def _find_marker_position(full_text: str, marker: str, search_from: int) -> int:
    if not marker:
        return -1

    pos = full_text.find(marker, search_from)
    if pos != -1:
        return pos

    collapsed_marker = re.sub(r"\s+", " ", marker).strip()
    collapsed_text = re.sub(r"\s+", " ", full_text)
    collapsed_pos = collapsed_text.find(collapsed_marker, search_from)
    if collapsed_pos != -1:
        return collapsed_pos

    return full_text.lower().find(marker.lower(), search_from)


def _slice_document_by_boundaries(
    full_text: str,
    boundaries: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    if not boundaries:
        raise ValueError("No chunk boundaries provided")

    indexed: List[Tuple[int, Dict[str, Any]]] = []
    search_from = 0

    for i, boundary in enumerate(boundaries):
        marker = (boundary.get("start_marker") or boundary.get("heading") or "").strip()
        if i == 0 and not marker:
            indexed.append((0, boundary))
            continue
        if not marker:
            logger.warning(f"Skipping boundary {i}: missing start_marker")
            continue

        pos = _find_marker_position(full_text, marker, search_from)
        if pos == -1:
            logger.warning(f"start_marker not found for chunk {i}: {marker[:80]!r}")
            continue

        indexed.append((pos, boundary))
        search_from = pos + max(len(marker), 1)

    if not indexed:
        raise ValueError("No valid start_marker positions found in document")

    indexed.sort(key=lambda item: item[0])
    if indexed[0][0] > 0:
        indexed[0] = (0, indexed[0][1])

    deduped: List[Tuple[int, Dict[str, Any]]] = []
    seen_positions: set[int] = set()
    for pos, boundary in indexed:
        if pos in seen_positions:
            continue
        seen_positions.add(pos)
        deduped.append((pos, boundary))

    sections: List[Dict[str, Any]] = []
    for i, (start, boundary) in enumerate(deduped):
        end = deduped[i + 1][0] if i + 1 < len(deduped) else len(full_text)
        text = full_text[start:end].strip()
        if not text:
            continue

        heading = boundary.get("heading") or ""
        if not isinstance(heading, str):
            heading = ""

        sections.append({
            "heading": heading.strip(),
            "text": text,
            "keywords": _normalize_llm_keywords(boundary.get("keywords")),
        })

    if not sections:
        raise ValueError("Boundary slicing produced no non-empty sections")

    return sections


def _normalize_llm_keywords(raw_keywords: Any) -> List[str]:
    if not isinstance(raw_keywords, list):
        return []

    seen: set[str] = set()
    keywords: List[str] = []
    for item in raw_keywords:
        if not isinstance(item, str):
            continue
        normalised = item.lower().strip()
        if normalised and normalised not in seen:
            seen.add(normalised)
            keywords.append(normalised)
    return keywords


def _parse_llm_split_response(raw: str, full_text: str) -> List[Dict[str, Any]]:
    """Parse LLM boundary output and slice the original document."""
    parsed = _extract_json_array(raw)
    if not parsed:
        raise ValueError("LLM returned empty JSON array")

    boundaries: List[Dict[str, Any]] = []
    for item in parsed:
        if isinstance(item, str):
            boundaries.append({
                "heading": "",
                "start_marker": item.strip(),
                "keywords": [],
            })
            continue

        if not isinstance(item, dict):
            continue

        text = item.get("text") or item.get("content") or item.get("chunk")
        if isinstance(text, str) and text.strip() and not item.get("start_marker"):
            heading = item.get("heading") or item.get("title") or ""
            if not isinstance(heading, str):
                heading = ""
            boundaries.append({
                "heading": heading.strip(),
                "start_marker": text.strip()[:120],
                "keywords": item.get("keywords"),
                "_full_text": text.strip(),
            })
            continue

        heading = item.get("heading") or item.get("title") or ""
        if not isinstance(heading, str):
            heading = ""

        boundaries.append({
            "heading": heading.strip(),
            "start_marker": (item.get("start_marker") or heading or "").strip(),
            "keywords": item.get("keywords"),
        })

    if not boundaries:
        raise ValueError("LLM returned no usable chunk boundaries")

    if all(boundary.get("_full_text") for boundary in boundaries):
        return [
            {
                "heading": boundary.get("heading", ""),
                "text": boundary["_full_text"],
                "keywords": _normalize_llm_keywords(boundary.get("keywords")),
            }
            for boundary in boundaries
        ]

    return _slice_document_by_boundaries(full_text, boundaries)


def _llm_chunk_document(
    all_content: str,
    all_pages: List[int],
) -> List[Dict[str, Any]]:
    """Split document text into semantic chunks using the LLM."""
    try:
        llm = get_llm_service().get_llm(
            temperature=0.0,
            max_tokens=8000,
            timeout=120,
        )
        prompt = _LLM_SPLIT_PROMPT.format(text=all_content)
        response = llm.invoke(prompt)
        raw = _extract_llm_text(response)

        sections = _parse_llm_split_response(raw, all_content)
        if len(sections) <= 1 and len(all_content) > 2000:
            raise ValueError(
                f"LLM produced only {len(sections)} section(s) for a long document"
            )

        logger.info(f"LLM split produced {len(sections)} sections")
        return [
            {
                "heading": sec["heading"],
                "content": sec["text"],
                "page_numbers": all_pages,
                "keywords": sec["keywords"],
            }
            for sec in sections
        ]

    except Exception as exc:
        logger.warning(
            f"LLM chunking failed ({exc}); response may have been invalid. "
            "Keeping single chunk.",
            exc_info=True,
        )
        return [{
            "heading": "",
            "content": all_content,
            "page_numbers": all_pages,
            "keywords": [],
        }]


# Matches runs of 4+ repeated separator chars (with optional spaces between runs)
# e.g. "===== ====" or "----" or "==== ============"
_SEPARATOR_SEGMENT_RE = re.compile(r"([=\-_*#~^]{4,}[\s]*){1,}")


def _strip_noise(text: str) -> str:
    """Remove known noise phrases and separator lines from content."""
    for phrase in _NOISE_PHRASES:
        text = re.sub(re.escape(phrase), "", text, flags=re.IGNORECASE)

    # Process line by line: strip separator segments from each line,
    # then drop the line entirely if nothing meaningful remains.
    lines = text.splitlines()
    cleaned = []
    for ln in lines:
        stripped = _SEPARATOR_SEGMENT_RE.sub("", ln).strip()
        if stripped:
            cleaned.append(stripped)

    text = "\n".join(cleaned)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def _block_text(block: Dict[str, Any]) -> str:
    return " ".join(l["text"] for l in block.get("lines", [])).strip()


def _table_to_text(rows: List[List[str]]) -> str:
    lines = []
    for row in rows:
        cells = [str(c).strip() for c in row if str(c).strip()]
        if cells:
            lines.append(" | ".join(cells))
    return "\n".join(lines)


def _median(values: List[float]) -> float:
    if not values:
        return 0.0
    sv  = sorted(values)
    mid = len(sv) // 2
    return sv[mid] if len(sv) % 2 == 1 else (sv[mid - 1] + sv[mid]) / 2.0


_INSURER_LEGAL_SUFFIXES = re.compile(
    r"\s+(insurance|ltd|limited|co|company|pvt|private|management|managers|amc)\b",
    re.IGNORECASE,
)


def _insurer_brand(insurer_name: str) -> str:
    """Return the bare brand prefix of an insurer name.

    e.g. "Axis Max Life Insurance" -> "Axis Max Life"
         "HDFC Life Insurance Co Ltd" -> "HDFC"
    """
    return _INSURER_LEGAL_SUFFIXES.sub("", insurer_name).strip()


def _build_nfo_name(insurer_name: str, product_name: str) -> str:
    """Combine insurer and fund name without duplicating the brand prefix.

    "Axis Max Life Insurance" + "Axis Max Life BSE 500 Fund"
      -> "Axis Max Life BSE 500 Fund"          (no prefix added)

    "Axis Max Life Insurance" + "BSE 500 Fund"
      -> "Axis Max Life Insurance - BSE 500 Fund"
    """
    if not insurer_name:
        return product_name

    brand = _insurer_brand(insurer_name).lower()
    if product_name.lower().startswith(brand):
        return product_name

    return f"{insurer_name} - {product_name}"


def _clean_product_name(raw: str) -> str:
    # Strip separator lines made of repeated punctuation (=, -, _, *, etc.)
    cleaned = re.sub(r"[=\-_*#~^]{3,}", " ", raw)
    # Replace remaining underscores/hyphens used as word separators
    cleaned = re.sub(r"[_\-]+", " ", cleaned)
    # Drop any leftover non-alphanumeric characters except spaces and dots
    cleaned = re.sub(r"[^\w\s.]", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned.title() if cleaned else "Unknown"
